version: '3.2'
 
services:
 elasticsearch:
   build:
     context: elasticsearch/
   volumes:
     - type: volume
       source: elasticsearch
       target: /usr/share/elasticsearch/data
   ports:
     - "9200:9200"
     - "9300:9300"
   environment:
     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
     ELASTIC_PASSWORD: elastic
     discovery.type: single-node
   networks:
     - elk_stack
 
 logstash:
   build:
     context: logstash/
   ports:
     - "5000:5000"
     - "9600:9600"
   environment:
     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
   networks:
     - elk_stack
   depends_on:
     - elasticsearch
 
 kibana:
  build:
     context: kibana/
  ports:
     - "5601:5601"
  networks:
     - elk_stack
  depends_on:
     - elasticsearch

 postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      PGUSER: app
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U app"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
     - elk_stack
     
 jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    restart: unless-stopped
    ports:
     - 8080:8080
    container_name: jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
     - elk_stack
    depends_on:
     - elasticsearch

 prometheus:
    container_name: prometheus
    image: quay.io/prometheus/prometheus:v2.34.0
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    user: root
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - "--storage.tsdb.retention.size=10GB"
    networks:
      - elk_stack
    ports:
      - "9090:9090"

 grafana:
    container_name: grafana
    image: grafana/grafana-oss:8.4.4
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-}
      GF_USERS_ALLOW_SIGN_UP: false
    ports:
      - 3000:3000
    networks:
      - elk_stack


networks:
 elk_stack:
   driver: bridge
   attachable: true
volumes:
 elasticsearch:
 pg_data:
 jenkins_data:

