global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: "docker"
    static_configs:
      - targets: ["172.17.0.1:9323"]

  - job_name: "docker-containers"
    metrics_path: '/actuator/prometheus'
    docker_sd_configs:
      - host: "http://172.17.0.1:2375"
        port: 8080
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: .+
        action: keep

  # - job_name: 'spring'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets:
  #       - 'bombardier:8080'
  #       - 'tps:8080'
